### ISSUE TITLE
Sponge DEV-444 Issue

### ISSUE THREAD

**Issue by m1zark** [Buuz135/ExtraChat#16]
I seem to be getting the following error when using the newest build of sponge... broadcasting works fine but the chat formatting does not work.

[18:21:25] [Server thread/ERROR] [Sponge/]: Could not pass ServerChatEvent to SpongePlugin:ExtraChat{1.3}
java.lang.NoSuchMethodError: org.spongepowered.api.event.entity.player.PlayerChatEvent.getPlayer()Lorg/spongepowered/api/entity/player/Player;
	at com.buuz135.extrachat.events.PlayerChat.onChat(PlayerChat.java:19) ~[PlayerChat.class:?]
	at org.spongepowered.common.event.handler.PlayerChatEventHandler_PlayerChat_onChat12.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredHandler.handle(RegisteredHandler.java:86) ~[RegisteredHandler.class:1.8-1371-2.1DEV-444+unknown-b444.git-unknown]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:248) [SpongeEventManager.class:1.8-1371-2.1DEV-444+unknown-b444.git-unknown]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:82) [SpongeModEventManager.class:1.8-1371-2.1DEV-444+unknown-b444.git-unknown]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:56) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:431) [ForgeHooks.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:796) [rj.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) [lu.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [lu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:709) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:655) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

**Comment by Buuz135** [comment]
What version of ExtraChat are you using?

**Comment by Buuz135** [comment]
It's fixed now, you can grab the new version from jenkins
