### ISSUE TITLE
Exception on launch

### ISSUE THREAD

**Issue by JoeSchmo2840** [Buuz135/ExtraChat#33]
[12:42:17] [Server thread/ERROR] [Sponge]: [Plugin Class: com.buuz135.extrachat.ExtraChat][Handler: init]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.spongepowered.mod.plugin.SpongeModPluginContainer.handleModStateEvent(SpongeModPluginContainer.java:126) [SpongeModPluginContainer.class:1.8-1371-2.1DEV-472+unknown-b472.git-unknown]
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:710) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:360) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [po.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 18 column 4
        at com.google.gson.internal.Streams.parse(Streams.java:56) ~[Streams.class:?]
        at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
        at com.buuz135.extrachat.config.JsonLoader.readChatGroups(JsonLoader.java:141) ~[JsonLoader.class:?]
        at com.buuz135.extrachat.config.JsonLoader.initJson(JsonLoader.java:48) ~[JsonLoader.class:?]
        at com.buuz135.extrachat.ExtraChat.init(ExtraChat.java:49) ~[ExtraChat.class:?]
        ... 31 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 18 column 4
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:465) ~[JsonReader.class:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
        at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:658) ~[TypeAdapters$25.class:?]
        at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642) ~[TypeAdapters$25.class:?]
        at com.google.gson.internal.Streams.parse(Streams.java:44) ~[Streams.class:?]
        at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
        at com.buuz135.extrachat.config.JsonLoader.readChatGroups(JsonLoader.java:141) ~[JsonLoader.class:?]
        at com.buuz135.extrachat.config.JsonLoader.initJson(JsonLoader.java:48) ~[JsonLoader.class:?]
        at com.buuz135.extrachat.ExtraChat.init(ExtraChat.java:49) ~[ExtraChat.class:?]
        ... 31 more

**Comment by Buuz135** [comment]
Is the same exception that you reported 2 times before, please read the responses in the other ones :(

**Comment by JoeSchmo2840** [comment]
Sorry I updated the plugin and figured it might be new
